---
extends: airbnb
env:
  node: true
  es6: true
parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaVersion: 7
rules:
  max-len: [1, 120, 2, {"ignoreUrls":true}]
  curly: [2, "multi-line"]
  comma-dangle: [2, always-multiline]
  eqeqeq: [2, "allow-null"]
  no-shadow: 1
  no-param-reassign: [2, { "props": false }]
  indent: [2, 4]
  padded-blocks: [2, { "switches": "always", "classes": "always" }]
  quotes:
    - 2
    - single
    - allowTemplateLiterals: true
settings:
  import/resolver:
    node:
      extensions:
        - .js

      # this is technically for identifying `node_modules` alternate names
      moduleDirectory:
        - node_modules # defaults to 'node_modules', but...
